### ISSUE TITLE
Can we use react-localstorage with flux architecture? 

### ISSUE THREAD

**Issue by RajeshHegde** [STRML/react-localstorage#11]
Can we use `react-localstorage` with flux architecture? 
This mixin seems to set the state while mounting, but in flux all the data will be stored in the `Store`, how to use `react-localstorage` with Flux.

**Comment by STRML** [comment]
Component-local state doesn't really play nice with Flux. 

If you want to use localstorage with top-level state, you'll have to define a localStorage-loading hook for your Flux architecture. Some exist.

This project is for components only.
