### ISSUE TITLE
DOM Exception 18 on iOS when cookies are disabled.

### ISSUE THREAD

**Issue by hongymagic** [STRML/react-localstorage#3]
Just by accessing `localStorage` [here on this line](https://github.com/STRML/react-localstorage/blob/master/react-localstorage.js#L4), it will cause iOS Safari to throw the above exception. Which can cause the entire react app to crash.

There is a fix though, take a look at how modernizr or [angular does it](https://github.com/angular-translate/angular-translate/commit/75504cbe2ddc0d18e08288b0fa4453356aaafe73).

**Comment by hongymagic** [comment]
One way to address this is to check for `localStorage` support, then export empty `{}` if it does not have the support. This way the the failures will be silent; and we could document the fact. If you don't like silent failures, perhaps produce a warning message in debug mode.

I am happy to send a PR, just want to gauge the approach before committing.

I don't think it would be ideal for each component to check for availability of the `localStorage` before including this mixin.

**Comment by STRML** [comment]
LocalStorage can be some serious BS sometimes - Chrome exposes the API
and simply clears the storage when the tab is closed in incognito,
Safari creates the window.localStorage object but throws when you try to
use it, and iOS throws when you just access the property - that's insane.

I think it's fine to simply disable the mirroring to localstorage if
accessing window.localStorage or window.localStorage.setItem() fails.
Then just console.warn() about it.
