### ISSUE TITLE
React 0.13 is moving away from mixins

### ISSUE THREAD

**Issue by rogierschouten** [STRML/react-localstorage#4]
Looks like a great package! Since React is slowly moving away from mixins, do you plan any support for the new context-based way of work?

**Comment by STRML** [comment]
No plans so far for that. I am not convinced that Mixins will be scrapped entirely; the whole 'higher-order component' pattern is really fiddly. We'll see what 0.14 brings.

**Comment by rogierschouten** [comment]
Fair enough. We don't use mixins because it doesn't  work well with
Typescript so I'd actually like to see them gone. But you're right, it's
pretty much in flux

**Comment by STRML** [comment]
Understood. This is a really simple module, I'm sure there's a way to get it working in TS, but I don't use TS personally so I wouldn't be the best one to port it.
