### ISSUE TITLE
Decorator / ES6(7) support

### ISSUE THREAD

**Issue by jonaswindey** [STRML/react-localstorage#7]
I'm using react with ES6 classes, which doesn't support mixins.
It would be nice if this package supported ES7 decorators or higher-order components (https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)

**Comment by STRML** [comment]
You can use `react-mixin` for now. I agree that an exported decorator would be nice.

**Comment by eriknyk** [comment]
+1

**Comment by STRML** [comment]
Try react-mixin (https://github.com/brigand/react-mixin)

**Comment by cassidoo** [comment]
Are there options outside of using `react-mixin` for this?

**Comment by STRML** [comment]
At this time, no, react-mixin does a great job with this though. Happy to accept any PR but I'd really rather not bloat the module if possible as a lot of people are still using `React.createClass({})`.

**Comment by raphaelparent** [comment]
:+1:

**Comment by f0rr0** [comment]
> a lot of people are still using React.createClass({}).

@STRML willing to accept the PR now?
