### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by morenoh149** [STRML/react-localstorage#8]
Using this module. When or how do I go about checking if the data is stale?

I'm using localstorage to store results from an api request. If a user returns to the app at a future date the info from localstorage must be checked for staleness and initiate another request to the api for fresh data.

**Comment by STRML** [comment]
That's out of the scope of this module and is absolutely application-specific. Try storing a date or a hash along with the data and checking against the server.

**Comment by morenoh149** [comment]
Yes. I store a date or hash.

And, for now, I check if it's stale in `componentDidUpdate` which shows the data loaded from localstorage on my app.
